macos-build-job:
  stage: build
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip3 install -r requirements.txt
    - python3 -m PyInstaller ./TheCuratorsMachine.spec
  tags:
    - AppleM1
  artifacts:
    paths:
      - dist/*.app/