LIGHT_BLUE = '#00BCff'
PRIMARY_COLOR = '#f4f4f2'
SECONDARY_COLOR = '#c0c0c0'

LIGHT_GRAY = '#e8e8e8'
DARK_GRAY = '#606060'

ICON_COLOR = '#35322f'

BLACK = '#000000'
WHITE = '#ffffff'
RED = '#ff0000'
GREEN = '#00ff00'
BLUE = '#0000ff'

Colors = {
    'LIGHT_BLUE': LIGHT_BLUE,
    'PRIMARY_COLOR': PRIMARY_COLOR,
    'SECONDARY_COLOR': SECONDARY_COLOR,
    'LIGHT_GRAY': LIGHT_GRAY,
    'DARK_GRAY': DARK_GRAY,
    'ICON_COLOR': ICON_COLOR,
    'BLACK': BLACK,
    'WHITE': WHITE,
    'RED': RED,
    'GREEN': GREEN,
    'BLUE': BLUE
}